# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [4]:
# 記得先 Import 正確的套件
import numpy as np

In [5]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [11]:
%timeit -n 10 a = 2

for i in Z:
    for j in i:
        for k in j:
            i = i + 1

40.5 ns ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit -n 10 a = 2

for d in Z.flat:
    d = d + 1

37.3 ns ± 14.7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit -n 10 a = 2

for e in np.nditer(Z):
    e = e + 1

41.9 ns ± 13 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [34]:
import numpy as np

Z = np.random.randint(0,10,50)
print(Z)

arr1= (np.bincount(Z).argmax())
print(np.bincount(Z))
print(arr1)

arr2=np.where(Z == arr1)[0]
print(arr2)

[3 9 5 0 1 2 0 5 9 9 1 6 0 4 4 7 6 4 4 8 8 4 0 3 6 5 7 7 3 4 6 7 3 3 1 1 7
 3 8 6 6 8 8 5 3 6 4 8 0 4]
[5 4 1 7 8 4 7 5 6 3]
4
[13 14 17 18 21 29 46 49]


In [6]:
'''
Your Code
'''

8

In [13]:
'''
Your Code
'''

array([ 0,  5,  9, 10, 11, 12, 18, 22, 38, 39, 41, 47, 49])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [15]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[7, 8, 1, 0, 9, 9]
[7, 8, 1, 0, 9, 9]
[[4, 2, 1, 5], [5, 3, 4, 1], [3, 9, 9, 6]]
[array([4, 2, 1, 5]), array([5, 3, 4, 1]), array([3, 9, 9, 6])]
[[[5, 6], [7, 2], [9, 0]], [[0, 6], [9, 1], [8, 8]]]
[array([[5, 6],
       [7, 2],
       [9, 0]]), array([[0, 6],
       [9, 1],
       [8, 8]])]


In [40]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7, 8, 1, 0, 9, 9]
b
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[[4, 2, 1, 5], [5, 3, 4, 1], [3, 9, 9, 6]]
b
b
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
b
[7 8 1 0 9 9]
[7 8 1 0 9 9]
[[[5, 6], [7, 2], [9, 0]], [[0, 6], [9, 1], [8, 8]]]
