# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [5]:
import numpy as np

a=np.zeros((2,3)) #產生由0組成的2*3矩陣
b=np.empty((2,3)) #產生由接近0的數字組成的2*3矩陣

print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

import numpy as np 

In [24]:
# 參考解答

a = np.random.rand(2, 3)
a = a * 1000

print(a.round())

[[652. 521. 235.]
 [372. 882. 130.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [27]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

print(a)
print(b)
print("------------------------")
print((a - b % 1) + m)

[[ 2.98563838  4.39962249  8.49607776]
 [ 5.04757081 11.75694315  0.31823357]]
[[ 2.98563838  4.39962249  8.49607776]
 [ 5.04757081 11.75694315  0.31823357]]
------------------------
[[22. 24. 28.]
 [25. 31. 20.]]
