# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [5]:
import numpy as np

a = np.random.rand(2,3)

print(a.sum())   #numpy 中才有的函式
print(np.sum(a)) #numpy 中才有的函式
print(sum(a))    #在python也可以使用,且在numpy中無法做2維陣列以上的加總


3.0424776890927125
3.0424776890927125
[1.44397628 0.48740417 1.11109724]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件

import numpy as np

#正規化是指讓數值都介於0~1之間

In [28]:
A = np.arange(25).reshape((5, 5))

A = (A - A.min()) / (A.max() - A.min())

print(A)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [25]:
import numpy as np

arr1 = np.random.rand(10) * 100
arr1 = arr1.round()
print(arr1)
arr1[arr1.argmax()] = -1 #利用遮罩後再使用argmax找出最大值
print(arr1)


[70. 38. 31. 67. 13. 72. 20. 55. 92. 79.]
[70. 38. 31. 67. 13. 72. 20. 55. -1. 79.]
