# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件
import numpy as np

In [10]:
a=np.arange(12)
a[ (a >= 3) & (a < 8) ] *= (-1)
print(a)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10 11]


2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [3]:
import numpy as np

A = np.random.rand(3, 6)

print(A)
print(A[ A > 0.5 ])
print(A[ A > 0.5 ].size)

[[0.10348972 0.49389362 0.31635901 0.76595284 0.74679101 0.10180387]
 [0.91728208 0.64328331 0.16315334 0.53549783 0.67460791 0.12426698]
 [0.54894643 0.6847993  0.43027565 0.29905766 0.6014171  0.73056245]]
[0.76595284 0.74679101 0.91728208 0.64328331 0.53549783 0.67460791
 0.54894643 0.6847993  0.6014171  0.73056245]
10
